version: '3.1'

services:
  mysql:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin01
      MYSQL_DATABASE: rasplus
      MYSQL_USER: felipe
      MYSQL_PASSWORD: admin01
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_container:/data/db

  mongo:
    image: mongo:5.0.31
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasmoo
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_container:/data/db

volumes:
  mysql_data_container:
  mongo_data_container:
    