version: '3.1'

services:
  mysql:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin01
      MYSQL_DATABASE: rasplus
      MYSQL_USER: felipe
      MYSQL_PASSWORD: admin01
    ports:
      - "3307:3306"